# Generated by Django 5.1.7 on 2025-03-13 21:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('convocatoria', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('tipo_convocatoria', models.CharField(max_length=255)),
                ('alcance', models.IntegerField()),
                ('objetivo', models.TextField()),
                ('presupuesto', models.BigIntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.BigIntegerField()),
                ('puesto_actual', models.CharField(max_length=255)),
                ('dependencia', models.CharField(max_length=255)),
                ('url_cvlac', models.CharField(max_length=255)),
                ('url_linkedin', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_evaluator', models.BooleanField(default=False)),
                ('is_researcher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoAliados',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=255)),
                ('tipo_aliado', models.CharField(max_length=255)),
                ('responsabilidades', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoProductos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=255)),
                ('habilidades', models.CharField(max_length=255)),
                ('experiencia', models.CharField(max_length=255)),
                ('conocimientos', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioConocimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conocimiento', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEstudios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estudio', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('year', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioExperiencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=255)),
                ('tiempo', models.IntegerField()),
                ('actividades', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioHabilidades',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('habilidad', models.CharField(max_length=255)),
                ('experiencia', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
