# Generated by Django 5.1.7 on 2025-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='alcance',
            field=models.TextField(),
        ),
    ]
