# Generated by Django 5.1.7 on 2025-03-14 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proyecto_alcance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioconocimiento',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conocimientos', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='usuarioestudios',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='usuarioexperiencia',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='usuariohabilidades',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='core.usuario'),
        ),
    ]
