# Generated by Django 5.1.7 on 2025-03-16 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarioconocimiento_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionProyecto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('rf_accuracy', models.FloatField()),
                ('rf_precision', models.FloatField()),
                ('rf_recall', models.FloatField()),
                ('rf_f1', models.FloatField()),
                ('knn_accuracy', models.FloatField()),
                ('knn_precision', models.FloatField()),
                ('knn_recall', models.FloatField()),
                ('knn_f1', models.FloatField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score_combinado', models.FloatField()),
                ('score_rf', models.FloatField()),
                ('score_knn', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('recomendacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_recomendados', to='core.recomendacionproyecto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'ordering': ['-score_combinado'],
            },
        ),
    ]
