# Generated by Django 5.1.7 on 2025-03-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recomendacionproyecto_recomendacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionusuario',
            name='match_conocimientos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recomendacionusuario',
            name='match_educacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recomendacionusuario',
            name='match_experiencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recomendacionusuario',
            name='match_habilidades',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recomendacionusuario',
            name='nivel_confianza',
            field=models.CharField(default='Media', max_length=50),
        ),
    ]
